### PR TITLE
:bug: Fix delete of csr if assets cannot be downloaded

### LINKED ISSUE #72: ClusterStackRelease is not getting deleted in case there are problems with release assets
/kind bug

**What steps did you take and what happened:**
If a clusterstackrelease has issues with release assets, then it never deletes the finalizer.

**What did you expect to happen:**
The finalizer should get removed even if there are issues with release assets, in order for the clusterstackrelease object to be deleted at all.

### PR DESCRIPTION
**Pull request by janiskemper**
**What this PR does / why we need it**:
Fix delete of ClusterStackRelease object in case there is a problem with the release assets.

Currently, the reconcileDelete function requires assets to be downloaded properly. If this is not the case, then the object does not get deleted and is stuck forever.

This happens for example when a user specifies a version of a clusterstack that does not exist. Then a ClusterStackRelease object is created, but will never get deleted again, because the downloading of the release assets fails, as the release does not exist.

Now we have an additional check to remove the finalizer without any further logic in case there is an issue with the release assets.

**Which issue(s) this PR fixes**:
Fixes #72

**TODOs**:
- [x] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Comment by janiskemper** [comment]
@kranurag7 can you plz test it in the following way:
1. Apply a clusterstack and specify a non-existing version
2. Verify that the clusterstackrelease for that version exists and show something like "release assets not downloaded" in the conditions
3. Remove the version from the list of the clusterstack
4. Check that the clusterstackrelease is getting deleted

**Review by kranurag7 — APPROVED** [review]
@janiskemper this looks good to me, the test mentioned above works!!

**Comment by janiskemper** [comment]
@kranurag7 linting doesn't work currently right? I guess this is safe to merge?!

**Comment by kranurag7** [comment]
> @kranurag7 linting doesn't work currently right? I guess this is safe to merge?!

Yes, until we have new builder image, the linting will continue to be in broken state. 
Ref: https://github.com/SovereignCloudStack/cluster-stack-operator/issues/164

**Pull request merged**
