### PR TITLE
:bug: Fix issue 231: Continue if cluster stack string is invalid

### LINKED ISSUE #231: Ignore irrelevent or wrong releases in autosubscribe
/kind bug

**What steps did you take and what happened:**
I get the following error while using autosubscribe and the current scs cluster-stacks repo: 
`failed to get clusterstack object from string \"openstack-scs-v5\": invalid format`.

This is because of a release in the Github repo that is not following the correct naming pattern of cluster stack releases.

**What did you expect to happen:**
We should just ignore it instead of throwing an error.

### PR DESCRIPTION
**Pull request by guettli**
**What this PR does / why we need it**:

If a release in the Github repo is not following the correct naming pattern of cluster stack releases, then up to now the the process failed.

This PR creates a Kuberentes Event, and then continues with the next release of the list.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #231 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Comment by chess-knight** [comment]
Hi there, I hit the same problem and proposed a solution here https://github.com/SovereignCloudStack/cluster-stack-operator/pull/238/commits/fba490d63fe8d80acf27bd33bb7a3ae6a4f8b908#diff-83f84407fa1b782bedd13dbe38772704c2516be07f1509b512ea481bcd84bc5d. What do you think?

**Comment by guettli** [comment]
> Hi there, I hit the similar problem and proposed a solution here [fba490d#diff-83f84407fa1b782bedd13dbe38772704c2516be07f1509b512ea481bcd84bc5d](https://github.com/SovereignCloudStack/cluster-stack-operator/commit/fba490d63fe8d80acf27bd33bb7a3ae6a4f8b908#diff-83f84407fa1b782bedd13dbe38772704c2516be07f1509b512ea481bcd84bc5d). What do you think about releases without name? I took `TagName` instead of `Name`.
> 
> I am also thinking about logic like take `Name` and if it doesn't exist, take `TagName`.

Since releases don't get created by hand, I think the current logic (to use `name`) is fine.

@janiskemper what do you think?

@chess-knight But this is a different topic. Maybe open an issue or PR about that, so we can discuss this at the appropriate place.

**Comment by chess-knight** [comment]
> Since releases don't get created by hand, I think the current logic (to use name) is fine.

Yeah, you are right, but still, the name of the release is not required by GitHub API https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release.

But you are right, let's discuss it elsewhere.

**Comment by janiskemper** [comment]
this should be a solution to the problem. We can, as you two probably concluded as well, think about possible improvements at another place!

**Review by janiskemper — APPROVED** [review]

**Pull request merged**
