### PR TITLE
:sparkles: Include Kubernetes version in helm template

### PR DESCRIPTION
**Pull request by chess-knight**
**What this PR does / why we need it**:
Helm charts can use `Capabilities.KubeVersion`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes SovereignCloudStack/cluster-stacks#143

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Review by janiskemper — APPROVED** [review]

**Comment by batistein** [comment]
@chess-knight While reviewing this PR, I noticed that a new flag was added without a strong reason behind it. 
There are reasons not to include these helm capabilities by design, as this would require testing the helm logic. Typically, it is best practice to avoid a lot of templating logic that goes beyond the Kubernetes version. Since the cluster stacks are mainly used for a very strong, deeply integrated lifecycle, it is better not to include these helm capabilities. 

Of course, I understand that this may seem convenient when using a third-party dependency. 
But if we want to add the build in capabilities then we should do it for all of them. Right now, for example, APIVersion is missing and would also be used in the same context.

**Comment by jschoone** [comment]
Hi @chess-knight and @janiskemper since this is approved, can it be merged?

**Comment by chess-knight** [comment]
It is strange. One unit test failed, but I merged only docs changes. Before that change, all tests passed.

**Comment by janiskemper** [comment]
I was successful in re-running ;)

**Pull request merged**
