### PR TITLE
📖 add docs for releasing cluster-stack-operator

### PR DESCRIPTION
**Pull request by kranurag7**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/SovereignCloudStack/cluster-stack-operator/issues/62

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Review by chess-knight — APPROVED** [review]
LGTM

**Review by michal-gubricky — APPROVED** [review]
lgtm

**Comment by jschoone** [comment]
Hi @kranurag7, is that still a Draft?

**Comment by kranurag7** [comment]
> Hi @kranurag7, is that still a Draft?

I wanted to add a note and I've done that via https://github.com/SovereignCloudStack/cluster-stack-operator/commit/94b951a5ff4ff0ec48ce8c4cbe38a5b8c2be8e9e 

Now, I'll mark this ready for review.

**Comment by jschoone** [comment]
> > Hi @kranurag7, is that still a Draft?
> 
> I wanted to add a note and I've done that via [94b951a](https://github.com/SovereignCloudStack/cluster-stack-operator/commit/94b951a5ff4ff0ec48ce8c4cbe38a5b8c2be8e9e)
> 
> Now, I'll mark this ready for review.

Thanks @kranurag7. Question to you and @batistein (as requested for review)

**Comment by kranurag7** [comment]
Yes, I think the approvals are still up to date here but still let's go through it again. 

@chess-knight @michal-gubricky I added on more commit about updating metadata.yaml when we change the minor version for the release. 

https://github.com/SovereignCloudStack/cluster-stack-operator/pull/79/commits/76681e2001106e404047058d09dc1aa1f31a7b59 

Please review it again and upon approval, let's get this patch merged into main.

**Review by batistein — APPROVED** [review]

**Pull request merged**
