### PR TITLE
✨ bump to CAPI 1.7.2

### PR DESCRIPTION
**Pull request by kranurag7**
**What this PR does / why we need it**:
this commit bumps cluster API to 1.7.2 version. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/SovereignCloudStack/cluster-stack-operator/issues/170

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Review by janiskemper — COMMENTED** [review]
is image/builder relevant as well?

**Comment by janiskemper** [comment]
> is image/builder relevant as well?

@kranurag7 what's your plan with the image/builder file? There seem to be some outdated dependencies?!

**Comment by kranurag7** [comment]
> > 
> 
> @kranurag7 what's your plan with the image/builder file? There seem to be some outdated dependencies?!

I'll create another PR for it and that should be something that's automatically updated by renovate bot. See https://github.com/SovereignCloudStack/cluster-stack-operator/issues/172

**Review by janiskemper — COMMENTED** [review]
lgtm. plz squash

**Review by janiskemper — APPROVED** [review]

**Pull request merged**
